name: Random Daily Commits

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "mobinahmedd"
          git config --global user.email "mobinahmed4321@gmail.com"

      - name: Generate Random Commits
        run: |
          # Get a random number of commits (0 to 4)
          NUM_COMMITS=$((RANDOM % 5))
          echo "Making $NUM_COMMITS commits today"

          if [ "$NUM_COMMITS" -gt 0 ]; then
            for i in $(seq 1 $NUM_COMMITS); do
              echo "$(date) - Random commit $i" >> random-commits.txt
              git add random-commits.txt
              git commit -m "Random commit $i on $(date)"
            done
          else
            echo "Skipping commits today."
          fi

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
