name: Generate Random Commits

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "mobinahmedd"
          git config --global user.email "mobinahmed4321@gmail.com"

      - name: Generate Random Commits
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Start date (2 years ago)
          START_DATE=$(date -d "2 years ago" +%s)
          # End date (yesterday)
          END_DATE=$(date -d "yesterday" +%s)

          # Iterate over each day in the last 2 years
          for ((timestamp=$START_DATE; timestamp<=$END_DATE; timestamp+=86400)); do
            # Randomly decide whether to commit (0 to 4 commits per day)
            NUM_COMMITS=$(( RANDOM % 5 ))
            
            if [ $NUM_COMMITS -gt 0 ]; then
              for ((i=0; i<$NUM_COMMITS; i++)); do
                # Set a random time within the day
                COMMIT_TIME=$(date -d "@$((timestamp + RANDOM % 86400))" --iso-8601=seconds)

                # Generate a commit
                echo "$COMMIT_TIME" > random-commit.txt
                git add random-commit.txt
                GIT_COMMITTER_DATE="$COMMIT_TIME" GIT_AUTHOR_DATE="$COMMIT_TIME" git commit -m "Random commit on $COMMIT_TIME"
              done
            fi
          done

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
